### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DavidGOrtega** [kunzite-app/008#1]
- [x] Configuration
  - [x] BasicAuth HTTP request
  - [x] Local file 
- [x] Contacts
  - [x] VCF
  - [ ] Google contacts
  - [ ] Microsoft Outlook
- [x] Calls
- [x] Transfers
  - [x] Blind
  - [x] Attended
- [x] AutoAnswer
- [x] "Numbers" or Caller IDs
- [x] Custom statuses
- [x] Video
- [x] Events
  - [x] Webhooks
  - [x] DOM
  - [ ] Integrations ![Commercial](https://img.shields.io/badge/-Commercial-blue)
    - [x] Hubspot
    - [x] Zendesk
    - [x] Zoho CRM
    - [x] Zoho Desk
    - [ ] Salesforce
    - [ ] [Gong](https://www.gong.io/)
    - [ ] [pipedrive](https://www.pipedrive.com/)
    - [ ] [kustomer](https://www.kustomer.com/)
    - [ ] [Front](https://www.front.com/)
- [ ] Multi language
- [x] AI - Speech2Text with embedded models
- [ ] AI - Summarization with embedded models ![Commercial](https://img.shields.io/badge/-Commercial-blue)
- [ ] AI - Sentiment analysis with embedded models ![Commercial](https://img.shields.io/badge/-Commercial-blue)
- [ ] AI - KPI insights extracted from conversation with embedded models ![Commercial](https://img.shields.io/badge/-Commercial-blue)
- [ ] AI - Programmable conversational agent with embedded LLMs or ChatGPT
- [ ] Multiple calls (simultaneously)
- [ ] Group calling / Video meetings
- [ ] Mobile
  - [ ] iOS
  - [ ] Android
- [ ] Styling ![Commercial](https://img.shields.io/badge/-Commercial-blue)
- [ ] Semantic Search within app ![Commercial](https://img.shields.io/badge/-Commercial-blue)
- [ ] CDRs Storage by user account
- [ ] Messaging
- [ ] Threaded history like whastapp
